repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint

# - repo: https://github.com/cheshirekow/cmake-format-precommit
#   rev: v0.6.13
#   hooks:
#   - id: cmake-lint

- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.1.1
  hooks:
  - id: clang-format
  - id: cppcheck
    args: [--enable=all, --suppress=unusedFunction, --suppress=missingIncludeSystem, -Isource]

# - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
#   rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
#   hooks:
#   - id: cpplint

- repo: https://github.com/Mercotui/pre-commit-qmllint
  rev: v1.0.0
  hooks:
  - id: qmllint
