dist: xenial

os:
  - linux

compiler:
  - gcc
  - clang

matrix:
  include:
    - name: "Desktop build and test"
      language: cpp
      before_install:
        - sudo apt-get -qq update
        - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
      install:
        - sudo apt-get -qq update
        - sudo apt-get install -qq qt512base qt512multimedia libgl-dev
        - source /opt/qt512/bin/qt512-env.sh

      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DANDROID=OFF
        - make all -j2
        - make check
    - name: "Android build"
      language: android
      android:
        components:
          - tools
          - platform-tools
          # The BuildTools version
          - build-tools-23.0.1
          # The SDK version
          - android 27
      install:
        # Install the NDK
        - echo y | sdkmanager "ndk-bundle"
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

notifications:
  email:
    on_success: never
    on_failure: always
