dist: bionic

os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get install -qq qtbase5-dev qtmultimedia5-dev qtdeclarative5-dev libqt5opengl5-dev

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DQt5Multimedia_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5" -DANDROID=OFF
    - make all -j2
    - make check
