dist: xenial

os:
  - linux

compiler:
  - gcc
  - clang

matrix:
  include:
    - name: "Desktop build and test"
      language: cpp
      before_install:
        - sudo apt-get -qq update
        - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
      install:
        - sudo apt-get -qq update
        - sudo apt-get install -qq qt57base qt57multimedia;
        - source /opt/qt512/bin/qt512-env.sh

      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DQt5Multimedia_DIR="/opt/Qt/5.7/gcc_64/lib/cmake/Qt5Multimedia/" -DANDROID=OFF
        - make all -j2
        - make check
    - name: "Android build"
      language: android

notifications:
  email:
    on_success: never
    on_failure: always
