dist: xenial

os:
  - linux

compiler:
  - gcc
  - clang

matrix:
  include:
    - name: "Desktop build and test"
      language: cpp
      addons:
      apt:
        sources:
          - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        update: true
        packages:
          - qt512base
          - qt512multimedia
          - libgl-dev
      install:
        - source /opt/qt512/bin/qt512-env.sh
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DANDROID=OFF
        - make all -j2
        - make check
    - name: "Android build"
      language: android
      jdk: openjdk10
      android:
        components:
          - tools # to get the new `repository-11.xml`
          - tools # to install Android SDK tools 25.1.x (x = 6 right now)
          - platform-tools
          # The BuildTools version
          - build-tools-27.0.1
          # The SDK version
          - android-27
      install:
        # Install the NDK
        - yes | sdkmanager "ndk-bundle"
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

notifications:
  email:
    on_success: never
    on_failure: always
