name: Articated CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/derpicated/articated-ci-container:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pre-commit
      run: pipx install pre-commit

    - name: Run pre-commit
      run: PATH=/github/home/.local/bin:$PATH pre-commit run --all-files

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mercotui/derpicated-articated-ci-container:latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create build dir
      run: mkdir ./build

    - name: Configure
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON
      env:
        QTDIR: /usr/lib/x86_64-linux-gnu/cmake/Qt5

    - name: Make
      working-directory: ./build
      run: make

    - name: Test
      working-directory: ./build
      run: make check
