name: Articated CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:groovy

    steps:
    - name: update PackageList
      run: apt-get update
    - name: install Dependencies
      run: apt-get install git cmake qtbase5-dev qtmultimedia5-dev qtdeclarative5-dev libqt5opengl5-dev

    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive

    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON
      env:
        QTDIR: /usr/lib/x86_64-linux-gnu/cmake/Qt5
    - name: make
      run: make

    - name: make check
      run: make check
