name: Articated CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/derpicated/articated-ci-qt6:latest
    steps:
      - uses: actions/checkout@v3

      - name: Run pre-commit
        run: pre-commit run --all-files

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}

  build:
    needs: [ lint ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/derpicated/articated-ci-qt6:latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Create build dir
        run: mkdir ./build

      - name: Configure
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON

      - name: Make
        working-directory: ./build
        run: make

      - name: Test
        working-directory: ./build
        run: make check
